src/home/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.Index, name='home'),
    # path('aboutus', views.AboutUs, name='aboutus'),

]

src/order/urls.py
from django.urls import include, path
from . import views

urlpatterns=[
    path('',views.index, name='index'),
   
    # path('shopcart/',views.shopcart, name="shopcart")
    # path('addtocart/<int:id>',views.addtocart,name="addtocart"),
    # path('deletetocart/<int:id>',views.deletetocart,name="deletetocart")
]

src/order/models.py
from django.db import models
from product.models import Product
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm
# Create your models here.
# from django.forms import ModelForm
class ShopCart(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    product= models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
    quantity = models.IntegerField()

    # def __str__(self):
    #     return self.product
    @property
    def price(self):
        if self.product_id is not None:
            return (self.product.price)
    @property
    def amount(self):
        if self.product_id is None:
            return 'None'
        return (self.quantity * self.product.price)
    @property
    def username(self):
        if self.user_id is None:
            return 'None'
        return (self.user.first_name)
 
    

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']

class Order(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('Accepted', 'Kabul Edildi'),
        ('Preaparing', 'Hazırlanıyor'),
        ('OnShipping', 'Kargo'),
        ('Completed', 'Tamamlandı'),
        ('Canceled', 'İptal Edildi'),
    )
    
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # Üye olmadan kullanım için kod gerekir
    code = models.CharField(max_length=5, editable=False )
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address','phone','city','country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('Accepted', 'Kabul Edildi.'),
        ('Canceled', 'Reddedildi.'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

src/order/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import ShopCart,ShopCartForm,OrderForm,Order,OrderProduct
from home.models import UserProfile,Setting
from product.models import Product
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.utils.crypto import get_random_string
# Create your views here.
def index(request):
    return HttpResponse('Order App')

@login_required(login_url='/login')# loginKontrolü için
def addtocart(request,id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    checkcontrol = ShopCart.objects.filter(product_id=id) # Ürün Sepette Varmı Filtreleme
    if checkcontrol:
        control = 1 # Ürün Sepette Var
    else:
        control = 0  # Ürün Sepette Yok
    if request.method == 'POST': # Ürün detail sayfasından Geldi İse(Detay İşlemleri İçin)
        form=ShopCartForm(request.POST)
        
        #****** ÜRÜN SEPETTE VAR MI KONTROLÜ   ********#         
        if form.is_valid():
            if control==1: # Olan Ürünün Üzerine Ekle  
                data = ShopCart.objects.get(product_id=id)                            
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:#Bu Üründen Hiç Yoksa Ekle
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()   
            request.session['cart_items'] = ShopCart.objects.filter(user_id= current_user.id).count()
            #Ürün Başarı İle Sepete Eklenmiştir. Teşekkür Ederiz
            return HttpResponseRedirect(url)                   
    else:  # İstek Direk Olarak Ürün Ekle Butonuna Basılarak Geldi İse(Listeden Sepete Ekleme İşlemleri İçin )
        if control==1: # Olan Ürünün Üzerine Ekle
            data = ShopCart.objects.get(product_id=id) 
            data.quantity += 1
            data.save()
        
        else:# Ürün Yoksa Ekle           
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()# veri tabanına kaydet
            # Ürün Başarı İle Sepete Eklenmiştir. Teşekkür Ederiz.
        request.session['cart_items'] = ShopCart.objects.filter(user_id= current_user.id).count()
        return HttpResponseRedirect(url)
    
    # Ürün Eklemede Hata Oluştu.   
    return HttpResponseRedirect(url)           
@login_required(login_url='/login') 
def deletetocart(request,id):
    current_user = request.user
    ShopCart.objects.filter(id=id).delete()
    request.session['cart_items'] = ShopCart.objects.filter(user_id= current_user.id).count()
    return HttpResponseRedirect("/order/shopcart")
def shopcart(request):
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id= current_user.id).count()
    total=0
    for rs in shopcart:
        total += rs.product.price * rs.quantity
    #return HttpResponse(str(total))
    context={'shopcart': shopcart,
             'total': total,
             }
    return render(request,'order/shoppingcart.html',context)


@login_required(login_url='/login')
def orderproduct(request):
    current_user = request.user # Talebin User Nesnesini current_userda tuttuk 
    shopcart = ShopCart.objects.filter(user_id=current_user.id) # Gelen current_user.id yi user_id ye aldık
    total = 0  
    for rs in shopcart:   
        total += rs.product.price * rs.quantity # total fiyat hesabı yapıldı

    if request.method == 'POST':  # Eğer Formdan Gönderildi ise Oldu İse
        form = OrderForm(request.POST)
        #return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............

            data = Order()
            data.first_name = form.cleaned_data['first_name'] #Ürün adeti getir formdan
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode= get_random_string(5).upper() # Rasgele Kod Üretildi.
            data.code =  ordercode
            data.save() # Veritabanı Kaydı Yapıldı.

            shopcart=ShopCart.objects.filter(user_id=current_user.id)
            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id     = data.id # Order Id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity
                detail.price    = rs.product.price
                detail.amount   = rs.amount         
                detail.save()
                ## Reduce quantity of sold product from Amount of Product  Stocktan Düşme
                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save() # ürün sayısı kaydedildi.
                #*************<>***************#


            ShopCart.objects.filter(user_id=current_user.id).delete() # Sepeti Temizle
            request.session['cart_items']=0  # Ürün Sayısını Sıfırla
            # messages.success(request, "Your Order has been completed. Thank you ")
            return render(request, 'order/order_completed.html',{'ordercode':ordercode})
        else:
            # messages.warning(request, form.errors) 
            return HttpResponse(form.errors)
            # return HttpResponseRedirect("/order/orderproduct")

    form= OrderForm()
    settings = Setting.objects.get(pk=1)
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {
               'settings':settings,
                'shopcart': shopcart,
               'total': total,
               'form': form,
               'profile': profile,
               }
    return render(request, 'order/order_form.html', context)

src/templates/order/order_completed.html
{% extends 'layout.html' %}

{% block title %} Şipariş Tamamlandı {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

<!-- {% block sidebar %} {% include 'sidebar.html' %} {% endblock %} -->

{% block content %}

    <!-- BREADCRUMB -->
    <section id="title" class="container-fluid wow fadeInDown">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h1>Ürün Sepeti</h1>
                </div>
                <div class="col-xs-6 text-right breadcrumbs">
                    <ul class="list-inline list-unstyled">
                        <!-- <li><a href="index-2.html">Ana Sayfa</a></li> -->
                        <li>/</li>
                        <li><a href="#">Alışveriş</a></li>
                        <li>/</li>
                        <li>Ürün Sepeti</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Complated</h3>
                        </div>
                        <hr>
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Siparişiniz Tamamlandı</h3>
                        <h3>Sipariş Kodu : {{ ordercode }}</h3>
                        <h3>Teşekkürler</h3>
                        <hr>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

src/templates/order/order_form.html
{% extends 'layout.html' %}
{% block title %} Sipariş Onay {% endblock %}
<!-- {% block description %} {{ settings.description }} {% endblock %}
{% block keywords %} {{ settings.keywords }} {% endblock %} -->
{% block favicon %}<link rel="shortcut icon" href="{{settings.icon.url}}"/>{% endblock %}



{% block content %}
<section id="title" class="container-fluid wow fadeInDown">
    <div class="container">
        <div class="row">
            <div class="col-xs-6">
                <h2>SİPARİŞ <small>ONAYLAMA</small></h2>
            </div>
            <div class="col-xs-6 text-right breadcrumbs">
                <ul class="list-inline list-unstyled">
                    <li><a href="index-2.html">Home</a></li>
                    <li>/</li>
                    <li>Product</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section id="content">

    <section id="blog-grid" class="container">

        <div class="row mt-2">

            


            
               

                <div  class="row">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="col-md-6">
                            <div>
    
                                <div class="section-title">
                                    <h4 class="title">Alışveriş Detay</h4>
                                </div>
                                
                                    <label for="id_first_name">İsim:</label>
                                    <input type="text" name="first_name"  value="{{ user.first_name }}" class="form-control" maxlength="10" required id="id_first_name"></p>
                                
                                
                                    <label for="id_last_name">Soyisim:</label>
                                    <input type="text" name="last_name"  value="{{ user.last_name }}" class="form-control" maxlength="10" required id="id_last_name"></p>
                               
                                
                                    <label for="id_address">Adres:</label>
                                    <input type="text" name="address" value="{{ profile.address }}" class="form-control" maxlength="150" id="id_address"></p>
                                
                                
                                    <label for="id_phone">Telefon:</label>
                                    <input type="text" name="phone"  value="{{ profile.phone }}"  class="form-control" maxlength="20" id="id_phone"></p>
                               
                                
                                    <p><label for="id_city">Şehir:</label>
                                        <select name="city" class="input-group" id="id_city">
                                            <option class="form-control" value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                            <option class="form-control" value="İstanbul">Istanbul</option>
                                            <option class="form-control" value="Ankara">Ankara</option>
                                            <option class="form-control" value="İzmir">Izmir</option>
                                            <option class="form-control" value="Bursa">Bursa</option>
                                            <option class="form-control" value="Konya">Konya</option>
                                            <option class="form-control" value="Yozgat">Yozgat</option>
                                        </select></p>
                                </div>
                                <div class="form-group">
                                    <p><label for="id_country">Country :</label>
                                        <input type="text" name="country" class="form-control" id="id_country" value="{{ profile.country }}"></p>
                                </div>
                                <div class="pull-right">
                                    <button  type="submit" class="btn btn-primary">Siparişi Tamamla</button>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="shiping-methods">
                                <div class="section-title">
                                    <h4 class="title">Ödeme Bilgileri</h4>
                                </div>
                                
                                <p><label for="total">Toplam Fiyat  </label>
                                    <input type="text" name="total" class="form-control" readonly value="{{ total }} USD"></p>
                                
                                <p><label for="holder">Credit Card Holder</label>
                                <input type="text" name="holder" class="form-control"  value=""></p>
                            
                                <p><label for="number">Credit Card Number</label>
                                <input type="text" name="number" class="form-control"  value=""></p>
                            
                                <p><label for="ecpdate">Credit Exp Date/Year</label>
                                    <input type="text" name="ecpdate" class="form-control"  placeholder="mm/yy"></p>
                            
                            
                                <p><label for="secnumber">Security Number</label>
                                    <input type="text" name="secnumber" class="form-control"  value=""></p>
                                
                            </div>
                        </div>
    
                    </form>    
                    </div>
                </div>
            
           


            

        </div>

    </div>

    <div class="space40"></div>

</section>
<!-- CONTENT END -->

<!-- CALL TO ACTION START -->

<!-- CALL TO ACTION END -->


{% endblock %}

src/templates/order/shoppingcart.html
{% extends 'layout.html' %}


{% block title %} Ürün Sepeti {% endblock %}
<!-- {% block description %} {{ settings.description }} {% endblock %}
{% block keywords %} {{ settings.keywords }} {% endblock %} -->
{% block favicon %}<link rel="shortcut icon" href="{{settings.icon.url}}"/>{% endblock %}
<!-- {% block sidebar %} {% include 'home/slider.html' %} {% endblock %} -->

{%block content%}
<section id="title" class="container-fluid wow fadeInDown">
    <div class="container">
        <div class="row">
            <div class="col-xs-6">
                <h1>Ürün Sepeti</h1>
            </div>
            <div class="col-xs-6 text-right breadcrumbs">
                <ul class="list-inline list-unstyled">
                    <li><a href="index-2.html">Home</a></li>
                    <li>/</li>
                    <li><a href="#">Shop</a></li>
                    <li>/</li>
                    <li>Ürün Sepeti</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- PAGE TITLE END -->


<!-- CONTENT START -->
<section id="content">

    <!-- shop section start -->
    <section id="cart" class="container">

        <!-- row start -->
        <div class="row">

            {%if shopcart%}
            <div class="col-md-8">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Ürün Adı</th>
                                <th>Ürün Fiyatı</th>
                                <th class="qtycolumn">Adet</th>
                                <th>Toplam Fiyat</th>
                                <th></th>
                            </tr>
                        </thead>
                        {% for rs in shopcart %}
                        <tbody>
                            
                            <tr>
                                <td><img alt="" class="img-responsive product-thumb" src="{{ rs.product.image.url }}"></td>
                                <td><a href="#">{{rs.product.title}}</a></td>
                                <td>{{rs.product.price}}</td>
                                <td>
                                    <div class="form-group">
                                        <input name="quantity" type="number" size="4" class="form-control" value="1" min="0" max="{{rs.product.amount}}" step="1">
                                    </div>
                                </td>
                                <td>{{rs.amount}}</td>
                                <td><a href="/order/deletetocart/{{rs.id}}"><i class="fa fa-times fa-fw"></i></a></td>
                            </tr>
                           
                            
                        </tbody>
                        {% endfor %}    
                    </table>

               </div>

               <div class="text-right">
                   <a href="/order/addtocart/{{product.id}}" class="btn btn-default"><i class="fa fa-refresh fa-fw"></i> Sepeti Güncelle</i></a>
               </div>

            </div>
            <!-- cart contents end -->


            <!-- cart total start -->
            <div class="col-md-4">
                <div class="text-left">
                    <h4><b>TOTALS</b> SEPET </h4>
                </div>

                <table class="table">
                    <tr>
                        <th>Sepet Total</th>
                        <td>{{total}}</td>
                    </tr>
                    <tr>
                        <th>Kargo</th>
                        <td>Free</td>
                    </tr>
                    <tr>
                        <th>Sipariş Total</th>
                        <td class="ordertotal">{{total}}</td>
                    </tr>
                </table>

                <div class="text-right">
                    <a href="/order/orderproduct" class="btn btn-primary btn-lg">Proceed to Checkout <i class="fa fa-arrow-circle-right fa-fw"></i></a>
                </div>

            </div>
           
            <!-- cart total end -->
            

        </div>
        <!-- row end -->
        {% else %}
        <div style="margin-bottom: 400px;"><h1 class="text-center" > Sepet Boş</h1></div>
        
        {% endif %}
    </section>
    <!-- shop section end -->

</section>

{%endblock%}